//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA
    {
        public decimal IDASISTENCIA { get; set; }
        public decimal IDESQUEMA { get; set; }
        public string IDCATEGORIATARIFA { get; set; }
        public decimal PORCENTAJE { get; set; }
        public decimal TIPOSALDO { get; set; }
        public decimal ESTADO { get; set; }
    }
}
