//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public string ID { get; set; }
        public string FISICO { get; set; }
        public string SALUDOID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string PAISID { get; set; }
        public string SEXO { get; set; }
        public string EMAIL { get; set; }
        public string IDENTIFICACION { get; set; }
        public string COMENTARIO { get; set; }
        public string CREADOR { get; set; }
        public Nullable<System.DateTime> CREADO { get; set; }
        public string MODIFICADOR { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public string CODSUENA { get; set; }
        public Nullable<int> REFERENCIA_CONTACTOS { get; set; }
    }
}
