//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesContactos : DbContext
    {
        public EntitiesContactos()
            : base("name=EntitiesContactos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_ACADEMIC_DEGREE> CAT_ACADEMIC_DEGREE { get; set; }
        public virtual DbSet<CAT_CURSO_ESTADO> CAT_CURSO_ESTADO { get; set; }
        public virtual DbSet<CAT_TIPO_IDENTIFIACION> CAT_TIPO_IDENTIFIACION { get; set; }
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
        public virtual DbSet<COURSES> COURSES { get; set; }
        public virtual DbSet<TIPO_CONTACTO> TIPO_CONTACTO { get; set; }
    }
}
