//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSES
    {
        public int COURSES1 { get; set; }
        public string COURSES_CODE { get; set; }
        public string COURSE_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string COST_CENTER { get; set; }
        public Nullable<int> CAT_TIPO_PROGRAMA { get; set; }
        public string OTHERS { get; set; }
        public Nullable<int> CAT_CURSO_ESTADO { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<int> APPROVED { get; set; }
        public Nullable<int> APPLYING { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public Nullable<decimal> TOTAL_SCOLARSHIP { get; set; }
        public Nullable<int> MAXIMUM_PARTICIPANTS { get; set; }
        public string LANGUAGE { get; set; }
        public string COURSE_URL { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string REFERENCE_MAIL { get; set; }
        public Nullable<System.DateTime> DEAD_LINE { get; set; }
        public Nullable<System.DateTime> ACCOUNTING_CLOSE { get; set; }
        public Nullable<int> WITHDREW { get; set; }
        public Nullable<decimal> ESTIMATED_COST { get; set; }
        public Nullable<decimal> TUITION_WAIVER { get; set; }
        public Nullable<decimal> TUITION_AID { get; set; }
    }
}
