//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO
    {
        public Nullable<int> NUMPREREGISTRO { get; set; }
        public Nullable<int> IDCONTACTO { get; set; }
        public string IDRESERVACION { get; set; }
        public string PROPOSITO { get; set; }
        public string IDGRUPO { get; set; }
        public string COMOENTERO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string NOMCURSO { get; set; }
        public string NUMCURSO { get; set; }
        public string ROLCURSO { get; set; }
        public string NOMPROYECTO { get; set; }
        public string INVERSIONES { get; set; }
        public string FUENTE { get; set; }
        public string RESOLUCION { get; set; }
        public string PERMISO { get; set; }
        public Nullable<System.DateTime> EXPIRACION { get; set; }
        public int CONTACTO { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string INSTITUTION { get; set; }
        public string CATEGORY { get; set; }
        public string GENDER { get; set; }
        public string PHONE { get; set; }
        public string PHONE_AREA_CODE { get; set; }
        public string FAX { get; set; }
        public string FAX_AREA_CODE { get; set; }
        public string EMERGENCY_CONTACT1 { get; set; }
        public string EMERGENCY_NUMBER1 { get; set; }
        public string EMERGENCY_E_MAIL1 { get; set; }
        public string EMERGENCY_CONTACT2 { get; set; }
        public string EMERGENCY_NUMBER2 { get; set; }
        public string EMERGENCY_E_MAIL2 { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<int> IDENTIFICATION_TYPE { get; set; }
        public string IDENTIFICATION { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public string COUNTRY_BIRTH { get; set; }
        public string NACIONALITY { get; set; }
        public string ETHNIC_GROUP { get; set; }
        public string ADDRESS_L1 { get; set; }
        public string AREA_OF_INTEREST { get; set; }
        public string ACADEMIC_DEGREE { get; set; }
        public string SECRET_QUESTION { get; set; }
        public string ANSWER { get; set; }
        public string PASSWORD { get; set; }
        public string GRUPO { get; set; }
        public string EMERGENCY_NUMBER1_CODE { get; set; }
        public string EMERGENCY_NUMBER2_CODE { get; set; }
        public string HOME_PHONE { get; set; }
        public string HOME_PHONE_AREA { get; set; }
        public string ADDRESS_COUNTRY { get; set; }
        public string ADDRESS_L2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<int> CAT_TIPO_ESTUDIANTE { get; set; }
        public string STATION { get; set; }
        public Nullable<bool> NO_DIETARY_RESTRICTIONS { get; set; }
        public Nullable<bool> VEGETARIAN { get; set; }
        public Nullable<bool> VEGAN { get; set; }
        public Nullable<bool> BEEF { get; set; }
        public Nullable<bool> CHICKEN { get; set; }
        public Nullable<bool> PORK { get; set; }
        public Nullable<bool> FISH { get; set; }
        public string OTHER_DIETARY { get; set; }
        public string COUNTRY_EMITS { get; set; }
        public Nullable<System.DateTime> CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public string NICKNAME { get; set; }
        public string DEPARTAMENT { get; set; }
        public string POSITION { get; set; }
        public string SKYPE { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<bool> CKOTHER_DIETARY_RESTRIC { get; set; }
        public string TXOTHER_DIETARY_RESTRIC { get; set; }
        public Nullable<bool> PRIN { get; set; }
        public string RELATIONSHIP_CONTACT1 { get; set; }
        public string RELATIONSHIP_CONTACT2 { get; set; }
        public string INSURANCE_COMPANY { get; set; }
        public string INSURANCE_NUMBER { get; set; }
        public Nullable<System.DateTime> INSURANCE_EXPIRATION { get; set; }
        public string ESPECIALIDAD { get; set; }
        public Nullable<bool> DATO_ESTACION { get; set; }
        public string CONTACTO_RESERVAS { get; set; }
        public string SHARE_INFORMATION { get; set; }
        public string PHONE_COUNTRY_CODE { get; set; }
        public string FAX_COUNTRY_CODE { get; set; }
        public string EMERGENCY_COUNTRY_NUM_CODE1 { get; set; }
        public string EMERGENCY_COUNTRY_NUM_CODE2 { get; set; }
        public string HORA_CREACION { get; set; }
        public string E_MAIL2 { get; set; }
    }
}
