//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE
    {
        public string ID { get; set; }
        public string PERSONA { get; set; }
        public string CLASE { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> NOTA { get; set; }
        public Nullable<decimal> BECA { get; set; }
    }
}
