
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RegistroVisitantes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PERSONA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PERSONA()
    {

        this.INFOVISITA = new HashSet<INFOVISITA>();

    }

    [Required]
    public string CEDULA { get; set; }

    [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
    public string NOMBRE { get; set; }

    [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
    public string APELLIDO { get; set; }

    [EmailAddress()]
    public string EMAIL { get; set; }
    
    [RegularExpression("[0-9]")]
    public string TELEFONO { get; set; }

    public string NACIONALIDAD { get; set; }

    public string PAIS { get; set; }

    public string ESTADO { get; set; }

    public string CIUDAD { get; set; }

    [StringLength(100)]
    public string DIRECCION { get; set; }

    public string POSICION { get; set; }

    public Nullable<int> INSTITUCION { get; set; }

    public string TITULO { get; set; }

    public string ROL { get; set; }

    public string GENERO { get; set; }

    public string COD_POSTAL { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<INFOVISITA> INFOVISITA { get; set; }

    public virtual V_INSTITUCION INSTITUCIONI { get; set; }

    public virtual V_PAISES NACIONALIDADI { get; set; }

    public virtual V_PAISES PAISI { get; set; }

}

}
