//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREREGISTRO
    {
        public int NUMPREREGISTRO { get; set; }
        public Nullable<int> IDCONTACTO { get; set; }
        public string IDRESERVACION { get; set; }
        [DisplayName("Purpose:")]
        public string PROPOSITO { get; set; }
        public string IDGRUPO { get; set; }
        [DisplayName("How you know?")]
        public string COMOENTERO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        [DisplayName("Course Name:")]
        public string NOMCURSO { get; set; }
        [DisplayName("Course Number:")]
        public string NUMCURSO { get; set; }
        [DisplayName("Participating as:")]
        public string ROLCURSO { get; set; }
        public string NOMPROYECTO { get; set; }
        public string INVERSIONES { get; set; }
        public string FUENTE { get; set; }
        public string RESOLUCION { get; set; }
        public string PERMISO { get; set; }
        public Nullable<System.DateTime> EXPIRACION { get; set; }
    
        public virtual CONTACTO CONTACTO { get; set; }
    }
}
