-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 27/05/2016 13:28:31
-- Generated from EDMX file: C:\Users\dsola\Source\Repos\RegistroVisitantes2\RegistroVisitantes\RegistroVisitantes\Models\registro.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "REGISTRO"."INFOVISITA" DROP CONSTRAINT "FK_INFOVISITA_PERSONA_FK" CASCADE;
-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "REGISTRO"."INFOVISITA";

-- DROP TABLE "REGISTRO"."PERSONA";

-- DROP TABLE "REGISTRO"."USUARIO";

-- DROP TABLE "REGISTRO"."V_PAISES";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'PERSONA'
CREATE TABLE "REGISTRO"."PERSONA" (
   "CEDULA" VARCHAR2(30 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(200 CHAR) ,
   "APELLIDO" VARCHAR2(200 CHAR) ,
   "EMAIL" VARCHAR2(200 CHAR) ,
   "TELEFONO" VARCHAR2(150 CHAR) ,
   "NACIONALIDAD" VARCHAR2(150 CHAR) ,
   "PAIS" VARCHAR2(150 CHAR) ,
   "ESTADO" VARCHAR2(150 CHAR) ,
   "CIUDAD" VARCHAR2(150 CHAR) ,
   "DIRECCION" VARCHAR2(400 CHAR) ,
   "POSICION" VARCHAR2(150 CHAR) ,
   "INSTITUCION" NUMBER(10) ,
   "TITULO" VARCHAR2(150 CHAR) ,
   "ROL" VARCHAR2(150 CHAR) ,
   "GENERO" CHAR(1 CHAR) ,
   "COD_POSTAL" VARCHAR2(150 CHAR) 
);

-- Creating table 'USUARIO'
CREATE TABLE "REGISTRO"."USUARIO" (
   "ID" NUMBER(32) NOT NULL,
   "NOMBRE" VARCHAR2(40 CHAR) ,
   "APELLIDO" VARCHAR2(40 CHAR) ,
   "EMAIL" VARCHAR2(40 CHAR) ,
   "USUAR" VARCHAR2(40 CHAR) NOT NULL,
   "CONTRASENA" VARCHAR2(40 CHAR) NOT NULL,
   "ROL" CHAR(1 CHAR) NOT NULL,
   "IDESTACION" VARCHAR2(26 CHAR) NOT NULL,
   "SEXO" CHAR(1 CHAR) 
);

-- Creating table 'V_ESTACION'
CREATE TABLE "REGISTRO"."V_ESTACION" (
   "ID" VARCHAR2(26 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(100 CHAR) NOT NULL,
   "SIGLAS" VARCHAR2(20 CHAR) ,
   "RESERVABLE" VARCHAR2(1 CHAR) 
);

-- Creating table 'V_RESERVACION'
CREATE TABLE "REGISTRO"."V_RESERVACION" (
   "ID" VARCHAR2(255 CHAR) NOT NULL,
   "ANFITRIONA" VARCHAR2(255 CHAR) ,
   "NUMERO" VARCHAR2(255 CHAR) NOT NULL,
   "ESTADO" VARCHAR2(255 CHAR) ,
   "PRIORIDAD" NUMBER(20) ,
   "GRUPO" VARCHAR2(255 CHAR) ,
   "ENTRA" DATE ,
   "ENTRAMTN" VARCHAR2(255 CHAR) ,
   "SALE" DATE ,
   "SALEMTN" VARCHAR2(255 CHAR) ,
   "RESPONSABLE" VARCHAR2(255 CHAR) ,
   "SOLICITANTE" VARCHAR2(255 CHAR) ,
   "NOTAS" VARCHAR2(4000 CHAR) ,
   "SOLICITADAEL" DATE ,
   "FORMAPAGO" VARCHAR2(255 CHAR) ,
   "SALDO" NUMBER(20,5) ,
   "CUENTACLIENTEKEY" VARCHAR2(255 CHAR) ,
   "CUENTACLIENTEOCLASS" VARCHAR2(255 CHAR) ,
   "ESTACION" VARCHAR2(26 CHAR) ,
   "MODIFICADOR" VARCHAR2(255 CHAR) ,
   "MODIFICADO" DATE ,
   "MONTO_PREPAGO" NUMBER(15,2) ,
   "REFERENCIA_PREPAGO" VARCHAR2(1000 CHAR) ,
   "PRIMERA_COMIDA" VARCHAR2(50 CHAR) ,
   "CREACION" NUMBER(19) ,
   "ULTIMA_MODIFICACION" NUMBER(19) ,
   "MODIFICA_RACK" VARCHAR2(255 CHAR) ,
   "MODIFICADO_RACK" VARCHAR2(255 CHAR) ,
   "FLAG" NUMBER(3) ,
   "URL" VARCHAR2(2000 CHAR) ,
   "TIPO" VARCHAR2(2 CHAR) 
);

-- Creating table 'INFOVISITA'
CREATE TABLE "REGISTRO"."INFOVISITA" (
   "ID_RESERVACION" VARCHAR2(255 CHAR) NOT NULL,
   "CEDULA" VARCHAR2(30 CHAR) NOT NULL,
   "NOMBRE_EMERGENCIA" VARCHAR2(400 CHAR) ,
   "TEL_EMERGENCIA" VARCHAR2(150 CHAR) ,
   "EMAIL_EMERGENCIA" VARCHAR2(150 CHAR) ,
   "REL_EMERGENCIA" VARCHAR2(150 CHAR) ,
   "COMIDA" VARCHAR2(300 CHAR) ,
   "CARNE" NUMBER(1) NOT NULL,
   "POLLO" NUMBER(1) NOT NULL,
   "PESCADO" NUMBER(1) NOT NULL,
   "CERDO" NUMBER(1) NOT NULL,
   "DIETA" VARCHAR2(150 CHAR) ,
   "OBSERVACIONES_DIETA" VARCHAR2(150 CHAR) ,
   "ALERGIAS" VARCHAR2(150 CHAR) ,
   "PROPOSITO" VARCHAR2(150 CHAR) ,
   "OTRO_PROPOSITO" VARCHAR2(150 CHAR) ,
   "COMO_ENTERO" VARCHAR2(150 CHAR) ,
   "FECHA" DATE ,
   "NOMBRE_CURSO" VARCHAR2(50 CHAR) ,
   "NUMERO_CURSO" VARCHAR2(30 CHAR) ,
   "ROL_CURSO" VARCHAR2(20 CHAR) ,
   "NOMBRE_PROYECTO" VARCHAR2(50 CHAR) ,
   "INVERSIONES" VARCHAR2(50 CHAR) ,
   "FUENTE" VARCHAR2(50 CHAR) ,
   "RESOLUCION" VARCHAR2(30 CHAR) ,
   "PERMISO" VARCHAR2(30 CHAR) ,
   "EXPIRACION" DATE ,
   "ESTADO" NUMBER(1) 
);

-- Creating table 'V_CONTACTO'
CREATE TABLE "REGISTRO"."V_CONTACTO" (
   "ID" VARCHAR2(30 CHAR) NOT NULL,
   "FISICO" CHAR(1 CHAR) NOT NULL,
   "SALUDOID" VARCHAR2(4 CHAR) ,
   "NOMBRE" VARCHAR2(80 CHAR) NOT NULL,
   "APELLIDOS" VARCHAR2(80 CHAR) ,
   "PAISID" VARCHAR2(26 CHAR) ,
   "SEXO" VARCHAR2(1 CHAR) ,
   "EMAIL" VARCHAR2(132 CHAR) ,
   "IDENTIFICACION" VARCHAR2(50 CHAR) ,
   "COMENTARIO" VARCHAR2(1000 CHAR) ,
   "CREADOR" VARCHAR2(100 CHAR) ,
   "CREADO" DATE ,
   "MODIFICADOR" VARCHAR2(100 CHAR) ,
   "MODIFICADO" DATE ,
   "CODSUENA" VARCHAR2(100 CHAR) ,
   "REFERENCIA_CONTACTOS" NUMBER(10) 
);

-- Creating table 'V_GRUPOANON'
CREATE TABLE "REGISTRO"."V_GRUPOANON" (
   "ID" VARCHAR2(30 CHAR) NOT NULL,
   "INFANTES" NUMBER(5) ,
   "NINOS" NUMBER(5) ,
   "MUJERES" NUMBER(5) ,
   "HOMBRES" NUMBER(5) 
);

-- Creating table 'V_GRUPORSRV'
CREATE TABLE "REGISTRO"."V_GRUPORSRV" (
   "ID" VARCHAR2(30 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(255 CHAR) ,
   "TIPO" VARCHAR2(3 CHAR) ,
   "DEL" DATE ,
   "AL" DATE ,
   "VEGGIES" NUMBER(5) ,
   "NOTASALIMENTACION" VARCHAR2(2000 CHAR) ,
   "PARTEDE" VARCHAR2(26 CHAR) ,
   "COORDINADOR" VARCHAR2(400 CHAR) 
);

-- Creating table 'V_INSTITUCION'
CREATE TABLE "REGISTRO"."V_INSTITUCION" (
   "CAT_INSTITUCION" NUMBER(10) NOT NULL,
   "DESCRIPCION" VARCHAR2(1000 CHAR) ,
   "FULL_NAME" VARCHAR2(1000 CHAR) ,
   "COUNTRY" VARCHAR2(20 CHAR) ,
   "X_SISTEMA" NUMBER(1) ,
   "CREADO" DATE 
);

-- Creating table 'V_PAISES'
CREATE TABLE "REGISTRO"."V_PAISES" (
   "CAT_PAISES" NUMBER(10) NOT NULL,
   "ISO" VARCHAR2(5 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(400 CHAR) NOT NULL,
   "GENTILICIO" VARCHAR2(400 CHAR) 
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "CEDULA"in table 'PERSONA'
ALTER TABLE "REGISTRO"."PERSONA"
ADD CONSTRAINT "PK_PERSONA"
   PRIMARY KEY ("CEDULA" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'USUARIO'
ALTER TABLE "REGISTRO"."USUARIO"
ADD CONSTRAINT "PK_USUARIO"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_ESTACION'
ALTER TABLE "REGISTRO"."V_ESTACION"
ADD CONSTRAINT "PK_V_ESTACION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_RESERVACION'
ALTER TABLE "REGISTRO"."V_RESERVACION"
ADD CONSTRAINT "PK_V_RESERVACION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID_RESERVACION", "CEDULA"in table 'INFOVISITA'
ALTER TABLE "REGISTRO"."INFOVISITA"
ADD CONSTRAINT "PK_INFOVISITA"
   PRIMARY KEY ("ID_RESERVACION", "CEDULA" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_CONTACTO'
ALTER TABLE "REGISTRO"."V_CONTACTO"
ADD CONSTRAINT "PK_V_CONTACTO"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_GRUPOANON'
ALTER TABLE "REGISTRO"."V_GRUPOANON"
ADD CONSTRAINT "PK_V_GRUPOANON"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_GRUPORSRV'
ALTER TABLE "REGISTRO"."V_GRUPORSRV"
ADD CONSTRAINT "PK_V_GRUPORSRV"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CAT_INSTITUCION"in table 'V_INSTITUCION'
ALTER TABLE "REGISTRO"."V_INSTITUCION"
ADD CONSTRAINT "PK_V_INSTITUCION"
   PRIMARY KEY ("CAT_INSTITUCION" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ISO"in table 'V_PAISES'
ALTER TABLE "REGISTRO"."V_PAISES"
ADD CONSTRAINT "PK_V_PAISES"
   PRIMARY KEY ("ISO" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "IDESTACION" in table 'USUARIO'
ALTER TABLE "REGISTRO"."USUARIO"
ADD CONSTRAINT "FK_USUARIOV_ESTACION"
   FOREIGN KEY ("IDESTACION")
   REFERENCES "REGISTRO"."V_ESTACION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_USUARIOV_ESTACION'
CREATE INDEX "IX_FK_USUARIOV_ESTACION"
ON "REGISTRO"."USUARIO"
   ("IDESTACION");

-- Creating foreign key on "CEDULA" in table 'INFOVISITA'
ALTER TABLE "REGISTRO"."INFOVISITA"
ADD CONSTRAINT "FK_INFOVISITA_PERSONA_FK"
   FOREIGN KEY ("CEDULA")
   REFERENCES "REGISTRO"."PERSONA"
       ("CEDULA")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_INFOVISITA_PERSONA_FK'
CREATE INDEX "IX_FK_INFOVISITA_PERSONA_FK"
ON "REGISTRO"."INFOVISITA"
   ("CEDULA");

-- Creating foreign key on "ID_RESERVACION" in table 'INFOVISITA'
ALTER TABLE "REGISTRO"."INFOVISITA"
ADD CONSTRAINT "FK_INFOVISITAV_RESERVACION"
   FOREIGN KEY ("ID_RESERVACION")
   REFERENCES "REGISTRO"."V_RESERVACION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_INFOVISITAV_RESERVACION'
CREATE INDEX "IX_FK_INFOVISITAV_RESERVACION"
ON "REGISTRO"."INFOVISITA"
   ("ID_RESERVACION");

-- Creating foreign key on "RESPONSABLE" in table 'V_RESERVACION'
ALTER TABLE "REGISTRO"."V_RESERVACION"
ADD CONSTRAINT "FK_V_RESERVACIONV_CONTACTO1"
   FOREIGN KEY ("RESPONSABLE")
   REFERENCES "REGISTRO"."V_CONTACTO"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_RESERVACIONV_CONTACTO1'
CREATE INDEX "IX_FK_V_RESERVACIONV_CONTACTO1"
ON "REGISTRO"."V_RESERVACION"
   ("RESPONSABLE");

-- Creating foreign key on "SOLICITANTE" in table 'V_RESERVACION'
ALTER TABLE "REGISTRO"."V_RESERVACION"
ADD CONSTRAINT "FK_V_RESERVACIONV_CONTACTO2"
   FOREIGN KEY ("SOLICITANTE")
   REFERENCES "REGISTRO"."V_CONTACTO"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_RESERVACIONV_CONTACTO2'
CREATE INDEX "IX_FK_V_RESERVACIONV_CONTACTO2"
ON "REGISTRO"."V_RESERVACION"
   ("SOLICITANTE");

-- Creating foreign key on "GRUPO" in table 'V_RESERVACION'
ALTER TABLE "REGISTRO"."V_RESERVACION"
ADD CONSTRAINT "FK_V_RESERVACIONV_GRUPOANON"
   FOREIGN KEY ("GRUPO")
   REFERENCES "REGISTRO"."V_GRUPOANON"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_RESERVACIONV_GRUPOANON'
CREATE INDEX "IX_FK_V_RESERVACIONV_GRUPOANON"
ON "REGISTRO"."V_RESERVACION"
   ("GRUPO");

-- Creating foreign key on "GRUPO" in table 'V_RESERVACION'
ALTER TABLE "REGISTRO"."V_RESERVACION"
ADD CONSTRAINT "FK_V_RESERVACIONV_GRUPORSRV"
   FOREIGN KEY ("GRUPO")
   REFERENCES "REGISTRO"."V_GRUPORSRV"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_RESERVACIONV_GRUPORSRV'
CREATE INDEX "IX_FK_V_RESERVACIONV_GRUPORSRV"
ON "REGISTRO"."V_RESERVACION"
   ("GRUPO");

-- Creating foreign key on "INSTITUCION" in table 'PERSONA'
ALTER TABLE "REGISTRO"."PERSONA"
ADD CONSTRAINT "FK_PERSONAV_INSTITUCION"
   FOREIGN KEY ("INSTITUCION")
   REFERENCES "REGISTRO"."V_INSTITUCION"
       ("CAT_INSTITUCION")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_PERSONAV_INSTITUCION'
CREATE INDEX "IX_FK_PERSONAV_INSTITUCION"
ON "REGISTRO"."PERSONA"
   ("INSTITUCION");

-- Creating foreign key on "NACIONALIDAD" in table 'PERSONA'
ALTER TABLE "REGISTRO"."PERSONA"
ADD CONSTRAINT "FK_PERSONAV_PAISES"
   FOREIGN KEY ("NACIONALIDAD")
   REFERENCES "REGISTRO"."V_PAISES"
       ("ISO")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_PERSONAV_PAISES'
CREATE INDEX "IX_FK_PERSONAV_PAISES"
ON "REGISTRO"."PERSONA"
   ("NACIONALIDAD");

-- Creating foreign key on "PAIS" in table 'PERSONA'
ALTER TABLE "REGISTRO"."PERSONA"
ADD CONSTRAINT "FK_V_PAISESPERSONA"
   FOREIGN KEY ("PAIS")
   REFERENCES "REGISTRO"."V_PAISES"
       ("ISO")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_PAISESPERSONA'
CREATE INDEX "IX_FK_V_PAISESPERSONA"
ON "REGISTRO"."PERSONA"
   ("PAIS");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
