
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RegistroVisitantes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class REPORTE
{

    public decimal ID { get; set; }

    public Nullable<System.DateTime> FECHADESDE { get; set; }

    public Nullable<System.DateTime> FECHAHASTA { get; set; }

    public string ANFITRIONA { get; set; }

    public string ESTACION { get; set; }

    public string TIPO { get; set; }

    public string NACIONALIDAD { get; set; }

}

}
