//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION_OTROS_INGRESOS
    {
        public string IDRESERVA { get; set; }
        public string IDCATTARIFA { get; set; }
        public short PAX { get; set; }
        public decimal MONTO { get; set; }
        public decimal IMPVT { get; set; }
        public decimal TOTAL { get; set; }
        public string MONEDA { get; set; }
        public string IDSERVICIOS { get; set; }
        public decimal PAGADO { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHAFIN { get; set; }
        public string NOMBRE { get; set; }
    }
}
