//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACIONITEM
    {
        public string ID { get; set; }
        public string RESERVACION { get; set; }
        public string RESERVABLE { get; set; }
        public string CATEGORIATARIFA { get; set; }
        public Nullable<bool> BLOQUEA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> DEL { get; set; }
        public Nullable<System.DateTime> AL { get; set; }
        public Nullable<decimal> PAX { get; set; }
        public decimal CLASIFICACIONTARIFA { get; set; }
        public string HORA { get; set; }
        public string RECURSO_ASIGNADO { get; set; }
    }
}
