//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_MIP
    {
        public string ID { get; set; }
        public string ANFITRIONA { get; set; }
        public string IDREFERENCIA { get; set; }
        public string FONDO { get; set; }
        public string GENERAL_LEDGER { get; set; }
        public string FUNCION { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string BECA { get; set; }
        public string FAS { get; set; }
        public decimal DEBE { get; set; }
        public decimal HABER { get; set; }
    }
}
