//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        public string ID { get; set; }
        public string ANFITRIONA { get; set; }
        public string NUMERO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> PRIORIDAD { get; set; }
        public string GRUPO { get; set; }
        public Nullable<System.DateTime> ENTRA { get; set; }
        public string ENTRAMTN { get; set; }
        public Nullable<System.DateTime> SALE { get; set; }
        public string SALEMTN { get; set; }
        public string RESPONSABLE { get; set; }
        public string SOLICITANTE { get; set; }
        public string NOTAS { get; set; }
        public Nullable<System.DateTime> SOLICITADAEL { get; set; }
        public string FORMAPAGO { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string CUENTACLIENTEKEY { get; set; }
        public string CUENTACLIENTEOCLASS { get; set; }
        public string ESTACION { get; set; }
        public string MODIFICADOR { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public Nullable<decimal> MONTO_PREPAGO { get; set; }
        public string REFERENCIA_PREPAGO { get; set; }
        public string PRIMERA_COMIDA { get; set; }
        public Nullable<long> CREACION { get; set; }
        public Nullable<long> ULTIMA_MODIFICACION { get; set; }
        public string MODIFICA_RACK { get; set; }
        public string MODIFICADO_RACK { get; set; }
        public Nullable<byte> FLAG { get; set; }
        public string URL { get; set; }
    }
}
