//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVABLE
    {
        public string ID { get; set; }
        public string CATEGORIA { get; set; }
        public string ESTACION { get; set; }
        public Nullable<short> CAPACIDAD { get; set; }
    
        public virtual ESTACION ESTACION1 { get; set; }
    }
}
