//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION_TARIFA
    {
        public string IDRESERVA { get; set; }
        public string IDCATTARIFA { get; set; }
        public short PAX { get; set; }
        public decimal MONTO { get; set; }
        public decimal IMPICT { get; set; }
        public decimal IMPVT { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<System.DateTime> DESDE { get; set; }
        public Nullable<System.DateTime> HASTA { get; set; }
        public Nullable<decimal> DIAS { get; set; }
        public decimal CLASIFICACIONTARIFA { get; set; }
        public decimal TIPOTARIFA { get; set; }
        public string VISITANTE { get; set; }
        public decimal PORCENTAJE { get; set; }
    }
}
