//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string PERSONA { get; set; }
        public string ORGANIZACION { get; set; }
        public string EDITABLE { get; set; }
        public string DELSISTEMA { get; set; }
    }
}
