
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RegistroVisitantes.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

public partial class Usuario
{

    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "El nombre es requerido.")]
    public string Nombre { get; set; }

    [Required(ErrorMessage = "El apellido es requerido.")]
    public string Apellido { get; set; }

    [Required(ErrorMessage = "El email es requerido.")]
    [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Por favor ingrese un corre electrónico válido.")]
    public string Email { get; set; }

    [Required(ErrorMessage = "El nombre de usuario es requerido.")]
    public string Username { get; set; }

    [Required(ErrorMessage = "La contraseña es requerida.")]
    [DataType(DataType.Password)]
    public string Password { get; set; }

}

}
