//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public string ANFITRION { get; set; }
        public string IDCONTACTO { get; set; }
        public string IDUSUARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE { get; set; }
        public string IDESTACION { get; set; }
        public decimal ESTADO { get; set; }
        public string CORREO { get; set; }
    }
}
