//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CONTACTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_CONTACTO()
        {
            this.RESPONSABLES = new HashSet<V_RESERVACION>();
            this.SOLICITANTES = new HashSet<V_RESERVACION>();
        }
    
        public string ID { get; set; }
        public string FISICO { get; set; }
        public string SALUDOID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string PAISID { get; set; }
        public string SEXO { get; set; }
        public string EMAIL { get; set; }
        public string IDENTIFICACION { get; set; }
        public string COMENTARIO { get; set; }
        public string CREADOR { get; set; }
        public Nullable<System.DateTime> CREADO { get; set; }
        public string MODIFICADOR { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public string CODSUENA { get; set; }
        public Nullable<int> REFERENCIA_CONTACTOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_RESERVACION> RESPONSABLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_RESERVACION> SOLICITANTES { get; set; }
    }
}
