
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RegistroVisitantes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class V_EMPLEADOS
{

    public string ID { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDOS { get; set; }

    public string EMAIL { get; set; }

    public string SEXO { get; set; }

    public string IDENTIFICACION { get; set; }

    public string NACIONALIDAD { get; set; }

    public Nullable<decimal> ESTADOCIVIL { get; set; }

}

}
