//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroVisitantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GRUPORSRV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_GRUPORSRV()
        {
            this.RESERVACIONES = new HashSet<V_RESERVACION>();
        }
    
        public string ID { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> DEL { get; set; }
        public Nullable<System.DateTime> AL { get; set; }
        public Nullable<short> VEGGIES { get; set; }
        public string NOTASALIMENTACION { get; set; }
        public string PARTEDE { get; set; }
        public string COORDINADOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_RESERVACION> RESERVACIONES { get; set; }
    }
}
