//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alergias.
        /// </summary>
        public static string oet_alergias {
            get {
                return ResourceManager.GetString("oet_alergias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string oet_apellidos {
            get {
                return ResourceManager.GetString("oet_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba su identificación o correo electrónico para completar sus datos.
        /// </summary>
        public static string oet_auto {
            get {
                return ResourceManager.GetString("oet_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carne.
        /// </summary>
        public static string oet_carne {
            get {
                return ResourceManager.GetString("oet_carne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerdo.
        /// </summary>
        public static string oet_cerdo {
            get {
                return ResourceManager.GetString("oet_cerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string oet_ciudad {
            get {
                return ResourceManager.GetString("oet_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string oet_codigo {
            get {
                return ResourceManager.GetString("oet_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación.
        /// </summary>
        public static string oet_contactoRelacion {
            get {
                return ResourceManager.GetString("oet_contactoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto de Emergencia.
        /// </summary>
        public static string oet_contactosTitulo {
            get {
                return ResourceManager.GetString("oet_contactosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string oet_correo {
            get {
                return ResourceManager.GetString("oet_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Curso.
        /// </summary>
        public static string oet_cursoNombre {
            get {
                return ResourceManager.GetString("oet_cursoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número del Curso.
        /// </summary>
        public static string oet_cursoNum {
            get {
                return ResourceManager.GetString("oet_cursoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participa Como.
        /// </summary>
        public static string oet_cursoRol {
            get {
                return ResourceManager.GetString("oet_cursoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta.
        /// </summary>
        public static string oet_dieta {
            get {
                return ResourceManager.GetString("oet_dieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Completa.
        /// </summary>
        public static string oet_direccion {
            get {
                return ResourceManager.GetString("oet_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar formulario.
        /// </summary>
        public static string oet_enviar {
            get {
                return ResourceManager.GetString("oet_enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string oet_fem {
            get {
                return ResourceManager.GetString("oet_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasaporte o cédula.
        /// </summary>
        public static string oet_id {
            get {
                return ResourceManager.GetString("oet_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institución.
        /// </summary>
        public static string oet_institucion {
            get {
                return ResourceManager.GetString("oet_institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string oet_investPosTitulo {
            get {
                return ResourceManager.GetString("oet_investPosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string oet_masc {
            get {
                return ResourceManager.GetString("oet_masc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionalidad.
        /// </summary>
        public static string oet_nacionalidad {
            get {
                return ResourceManager.GetString("oet_nacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string oet_nombre {
            get {
                return ResourceManager.GetString("oet_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otras Restricciones Dietarias.
        /// </summary>
        public static string oet_otrasRes {
            get {
                return ResourceManager.GetString("oet_otrasRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string oet_otro {
            get {
                return ResourceManager.GetString("oet_otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string oet_pais {
            get {
                return ResourceManager.GetString("oet_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Personal.
        /// </summary>
        public static string oet_personal {
            get {
                return ResourceManager.GetString("oet_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pescado.
        /// </summary>
        public static string oet_pescado {
            get {
                return ResourceManager.GetString("oet_pescado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pollo.
        /// </summary>
        public static string oet_pollo {
            get {
                return ResourceManager.GetString("oet_pollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voluntario.
        /// </summary>
        public static string oet_pos1 {
            get {
                return ResourceManager.GetString("oet_pos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal superior.
        /// </summary>
        public static string oet_pos10 {
            get {
                return ResourceManager.GetString("oet_pos10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Investigador principal.
        /// </summary>
        public static string oet_pos11 {
            get {
                return ResourceManager.GetString("oet_pos11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string oet_pos12 {
            get {
                return ResourceManager.GetString("oet_pos12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interino.
        /// </summary>
        public static string oet_pos2 {
            get {
                return ResourceManager.GetString("oet_pos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente de campo.
        /// </summary>
        public static string oet_pos3 {
            get {
                return ResourceManager.GetString("oet_pos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Técnico.
        /// </summary>
        public static string oet_pos4 {
            get {
                return ResourceManager.GetString("oet_pos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string oet_pos5 {
            get {
                return ResourceManager.GetString("oet_pos5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colaborador.
        /// </summary>
        public static string oet_pos6 {
            get {
                return ResourceManager.GetString("oet_pos6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinador.
        /// </summary>
        public static string oet_pos7 {
            get {
                return ResourceManager.GetString("oet_pos7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor.
        /// </summary>
        public static string oet_pos8 {
            get {
                return ResourceManager.GetString("oet_pos8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor.
        /// </summary>
        public static string oet_pos9 {
            get {
                return ResourceManager.GetString("oet_pos9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string oet_posicion {
            get {
                return ResourceManager.GetString("oet_posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencia de Carnes.
        /// </summary>
        public static string oet_preferencias {
            get {
                return ResourceManager.GetString("oet_preferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Científico visitante (sin proyectos en la estación).
        /// </summary>
        public static string oet_prop1 {
            get {
                return ResourceManager.GetString("oet_prop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal OET (en trabajo, no cubierto por otras categorías).
        /// </summary>
        public static string oet_prop10 {
            get {
                return ResourceManager.GetString("oet_prop10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string oet_prop11 {
            get {
                return ResourceManager.GetString("oet_prop11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Investigación (con proyecto en la estación).
        /// </summary>
        public static string oet_prop2 {
            get {
                return ResourceManager.GetString("oet_prop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso de pregrado.
        /// </summary>
        public static string oet_prop3 {
            get {
                return ResourceManager.GetString("oet_prop3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso de posgrado.
        /// </summary>
        public static string oet_prop4 {
            get {
                return ResourceManager.GetString("oet_prop4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso de extensión universitaria.
        /// </summary>
        public static string oet_prop5 {
            get {
                return ResourceManager.GetString("oet_prop5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de Educación Ambiental.
        /// </summary>
        public static string oet_prop6 {
            get {
                return ResourceManager.GetString("oet_prop6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visitante de historial natural.
        /// </summary>
        public static string oet_prop7 {
            get {
                return ResourceManager.GetString("oet_prop7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento especial-reunión.
        /// </summary>
        public static string oet_prop8 {
            get {
                return ResourceManager.GetString("oet_prop8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodista (reportero, escritor, filmación).
        /// </summary>
        public static string oet_prop9 {
            get {
                return ResourceManager.GetString("oet_prop9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propósito.
        /// </summary>
        public static string oet_proposito {
            get {
                return ResourceManager.GetString("oet_proposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propósito de la Visita.
        /// </summary>
        public static string oet_propositoTitulo {
            get {
                return ResourceManager.GetString("oet_propositoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restricciones Dietarias y Alergias.
        /// </summary>
        public static string oet_resTitulo {
            get {
                return ResourceManager.GetString("oet_resTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string oet_rol1 {
            get {
                return ResourceManager.GetString("oet_rol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesor(a).
        /// </summary>
        public static string oet_rol2 {
            get {
                return ResourceManager.GetString("oet_rol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinador.
        /// </summary>
        public static string oet_rol3 {
            get {
                return ResourceManager.GetString("oet_rol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente.
        /// </summary>
        public static string oet_rol4 {
            get {
                return ResourceManager.GetString("oet_rol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        public static string oet_rol5 {
            get {
                return ResourceManager.GetString("oet_rol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        public static string oet_sexo {
            get {
                return ResourceManager.GetString("oet_sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin restricción.
        /// </summary>
        public static string oet_sinrestr {
            get {
                return ResourceManager.GetString("oet_sinrestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo para Participantes de Cursos.
        /// </summary>
        public static string oet_solocursos {
            get {
                return ResourceManager.GetString("oet_solocursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string oet_telefono {
            get {
                return ResourceManager.GetString("oet_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario de Registro.
        /// </summary>
        public static string oet_titulo {
            get {
                return ResourceManager.GetString("oet_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título (Sr., Sra., Dr., otro).
        /// </summary>
        public static string oet_tituloPer {
            get {
                return ResourceManager.GetString("oet_tituloPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegano.
        /// </summary>
        public static string oet_vegano {
            get {
                return ResourceManager.GetString("oet_vegano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegetariano.
        /// </summary>
        public static string oet_vege {
            get {
                return ResourceManager.GetString("oet_vege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He sido debidamente informado(a) que la visita a las instalaciones de la Organización para Estudios Tropicales (OET) conlleva a riesgos inherentes a estaciones biológicas, tales como transitar por senderos o áreas resbalosas, húmedas y cubiertas de follaje y árboles circundantes. Asimismo, que en la zona a visitar existen serpientes y otros animales con el consabido riesgo de mordeduras y que puedan darse picaduras de insectos de cualquier naturaleza. También manifiesto que no tengo ningún impedimento de sa [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string oet_waiver {
            get {
                return ResourceManager.GetString("oet_waiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renuncia de Responsabilidad.
        /// </summary>
        public static string oet_waiverTitulo {
            get {
                return ResourceManager.GetString("oet_waiverTitulo", resourceCulture);
            }
        }
    }
}
