//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string eot_waiver {
            get {
                return ResourceManager.GetString("eot_waiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alergias.
        /// </summary>
        public static string oet_alergias {
            get {
                return ResourceManager.GetString("oet_alergias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string oet_apellidos {
            get {
                return ResourceManager.GetString("oet_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string oet_ciudad {
            get {
                return ResourceManager.GetString("oet_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string oet_codigo {
            get {
                return ResourceManager.GetString("oet_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación.
        /// </summary>
        public static string oet_contactoRelacion {
            get {
                return ResourceManager.GetString("oet_contactoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto de Emergencia.
        /// </summary>
        public static string oet_contactosTitulo {
            get {
                return ResourceManager.GetString("oet_contactosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string oet_correo {
            get {
                return ResourceManager.GetString("oet_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número del Curso.
        /// </summary>
        public static string oet_cursoNum {
            get {
                return ResourceManager.GetString("oet_cursoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participa Como.
        /// </summary>
        public static string oet_cursoRol {
            get {
                return ResourceManager.GetString("oet_cursoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Curso.
        /// </summary>
        public static string oet_cursoTitulo {
            get {
                return ResourceManager.GetString("oet_cursoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta.
        /// </summary>
        public static string oet_dieta {
            get {
                return ResourceManager.GetString("oet_dieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Completa.
        /// </summary>
        public static string oet_direccion {
            get {
                return ResourceManager.GetString("oet_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasaporte o cédula.
        /// </summary>
        public static string oet_id {
            get {
                return ResourceManager.GetString("oet_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institución.
        /// </summary>
        public static string oet_institucion {
            get {
                return ResourceManager.GetString("oet_institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionalidad.
        /// </summary>
        public static string oet_nacionalidad {
            get {
                return ResourceManager.GetString("oet_nacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string oet_nombre {
            get {
                return ResourceManager.GetString("oet_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otras Restricciones Dietarias.
        /// </summary>
        public static string oet_otrasRes {
            get {
                return ResourceManager.GetString("oet_otrasRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string oet_pais {
            get {
                return ResourceManager.GetString("oet_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Personal.
        /// </summary>
        public static string oet_personal {
            get {
                return ResourceManager.GetString("oet_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string oet_posicion {
            get {
                return ResourceManager.GetString("oet_posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencia de Carnes.
        /// </summary>
        public static string oet_preferencias {
            get {
                return ResourceManager.GetString("oet_preferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propósito.
        /// </summary>
        public static string oet_proposito {
            get {
                return ResourceManager.GetString("oet_proposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propósito de la Visita.
        /// </summary>
        public static string oet_propositoTitulo {
            get {
                return ResourceManager.GetString("oet_propositoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restricciones Dietarias y Alergias.
        /// </summary>
        public static string oet_resTititulo {
            get {
                return ResourceManager.GetString("oet_resTititulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        public static string oet_sexo {
            get {
                return ResourceManager.GetString("oet_sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo para Participantes de Cursos.
        /// </summary>
        public static string oet_solocursos {
            get {
                return ResourceManager.GetString("oet_solocursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string oet_telefono {
            get {
                return ResourceManager.GetString("oet_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario de Registro.
        /// </summary>
        public static string oet_titulo {
            get {
                return ResourceManager.GetString("oet_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título (Sr., Sra., Dr., otro).
        /// </summary>
        public static string oet_tituloPer {
            get {
                return ResourceManager.GetString("oet_tituloPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renuncia de Responsabilidad.
        /// </summary>
        public static string oet_waiverTitulo {
            get {
                return ResourceManager.GetString("oet_waiverTitulo", resourceCulture);
            }
        }
    }
}
