//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string aceptarInst {
            get {
                return ResourceManager.GetString("aceptarInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancelarInst {
            get {
                return ResourceManager.GetString("cancelarInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string descripInst {
            get {
                return ResourceManager.GetString("descripInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo encontró este lugar?.
        /// </summary>
        public static string es_como {
            get {
                return ResourceManager.GetString("es_como", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He sido debidamente informado(a) que la visita a las instalaciones de la Organización para Estudios Tropicales (OET) conlleva a riesgos inherentes a estaciones biológicas, tales como transitar por senderos o áreas resbalosas, húmedas y cubiertas de follaje y árboles circundantes. Asimismo, que en la zona a visitar existen serpientes y otros animales con el consabido riesgo de mordeduras y que puedan darse picaduras de insectos de cualquier naturaleza. También manifiesto que no tengo ningún impedimento de sa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string es_waiver {
            get {
                return ResourceManager.GetString("es_waiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string esintro_back {
            get {
                return ResourceManager.GetString("esintro_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francés.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La institución ha sido añadida.
        /// </summary>
        public static string insercionCorrecta {
            get {
                return ResourceManager.GetString("insercionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error añadiendo la institución.
        /// </summary>
        public static string insercionMala {
            get {
                return ResourceManager.GetString("insercionMala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su información se ha enviado correctamente !.
        /// </summary>
        public static string mensajeCorrecto {
            get {
                return ResourceManager.GetString("mensajeCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo ciertos problemas, intente nuevamente!.
        /// </summary>
        public static string mensajeErroneo {
            get {
                return ResourceManager.GetString("mensajeErroneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxito!.
        /// </summary>
        public static string mensajeTitulo {
            get {
                return ResourceManager.GetString("mensajeTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string nombreInst {
            get {
                return ResourceManager.GetString("nombreInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergias.
        /// </summary>
        public static string oet_alergias {
            get {
                return ResourceManager.GetString("oet_alergias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string oet_apellidos {
            get {
                return ResourceManager.GetString("oet_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba su identificación o correo electrónico para completar sus datos.
        /// </summary>
        public static string oet_auto {
            get {
                return ResourceManager.GetString("oet_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carne.
        /// </summary>
        public static string oet_carne {
            get {
                return ResourceManager.GetString("oet_carne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerdo.
        /// </summary>
        public static string oet_cerdo {
            get {
                return ResourceManager.GetString("oet_cerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string oet_ciudad {
            get {
                return ResourceManager.GetString("oet_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string oet_codigo {
            get {
                return ResourceManager.GetString("oet_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación.
        /// </summary>
        public static string oet_contactoRelacion {
            get {
                return ResourceManager.GetString("oet_contactoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto de Emergencia.
        /// </summary>
        public static string oet_contactosTitulo {
            get {
                return ResourceManager.GetString("oet_contactosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string oet_correo {
            get {
                return ResourceManager.GetString("oet_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Curso.
        /// </summary>
        public static string oet_cursoNombre {
            get {
                return ResourceManager.GetString("oet_cursoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número del Curso.
        /// </summary>
        public static string oet_cursoNum {
            get {
                return ResourceManager.GetString("oet_cursoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participa Como.
        /// </summary>
        public static string oet_cursoRol {
            get {
                return ResourceManager.GetString("oet_cursoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieta.
        /// </summary>
        public static string oet_dieta {
            get {
                return ResourceManager.GetString("oet_dieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Completa.
        /// </summary>
        public static string oet_direccion {
            get {
                return ResourceManager.GetString("oet_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string oet_edit {
            get {
                return ResourceManager.GetString("oet_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar formulario.
        /// </summary>
        public static string oet_enviar {
            get {
                return ResourceManager.GetString("oet_enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        public static string oet_fem {
            get {
                return ResourceManager.GetString("oet_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string oet_guardar {
            get {
                return ResourceManager.GetString("oet_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasaporte o cédula.
        /// </summary>
        public static string oet_id {
            get {
                return ResourceManager.GetString("oet_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institución.
        /// </summary>
        public static string oet_institucion {
            get {
                return ResourceManager.GetString("oet_institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        public static string oet_investPosTitulo {
            get {
                return ResourceManager.GetString("oet_investPosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string oet_masc {
            get {
                return ResourceManager.GetString("oet_masc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidad.
        /// </summary>
        public static string oet_nacionalidad {
            get {
                return ResourceManager.GetString("oet_nacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string oet_nombre {
            get {
                return ResourceManager.GetString("oet_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otras Restricciones Dietarias.
        /// </summary>
        public static string oet_otrasRes {
            get {
                return ResourceManager.GetString("oet_otrasRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string oet_otro {
            get {
                return ResourceManager.GetString("oet_otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string oet_pais {
            get {
                return ResourceManager.GetString("oet_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información Personal.
        /// </summary>
        public static string oet_personal {
            get {
                return ResourceManager.GetString("oet_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pescado.
        /// </summary>
        public static string oet_pescado {
            get {
                return ResourceManager.GetString("oet_pescado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollo.
        /// </summary>
        public static string oet_pollo {
            get {
                return ResourceManager.GetString("oet_pollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voluntario.
        /// </summary>
        public static string oet_pos1 {
            get {
                return ResourceManager.GetString("oet_pos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal superior.
        /// </summary>
        public static string oet_pos10 {
            get {
                return ResourceManager.GetString("oet_pos10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigador principal.
        /// </summary>
        public static string oet_pos11 {
            get {
                return ResourceManager.GetString("oet_pos11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string oet_pos12 {
            get {
                return ResourceManager.GetString("oet_pos12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interino.
        /// </summary>
        public static string oet_pos2 {
            get {
                return ResourceManager.GetString("oet_pos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistente de campo.
        /// </summary>
        public static string oet_pos3 {
            get {
                return ResourceManager.GetString("oet_pos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnico.
        /// </summary>
        public static string oet_pos4 {
            get {
                return ResourceManager.GetString("oet_pos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante.
        /// </summary>
        public static string oet_pos5 {
            get {
                return ResourceManager.GetString("oet_pos5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador.
        /// </summary>
        public static string oet_pos6 {
            get {
                return ResourceManager.GetString("oet_pos6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinador.
        /// </summary>
        public static string oet_pos7 {
            get {
                return ResourceManager.GetString("oet_pos7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string oet_pos8 {
            get {
                return ResourceManager.GetString("oet_pos8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor.
        /// </summary>
        public static string oet_pos9 {
            get {
                return ResourceManager.GetString("oet_pos9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        public static string oet_posicion {
            get {
                return ResourceManager.GetString("oet_posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferencia de Carnes.
        /// </summary>
        public static string oet_preferencias {
            get {
                return ResourceManager.GetString("oet_preferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Científico visitante (sin proyectos en la estación).
        /// </summary>
        public static string oet_prop1 {
            get {
                return ResourceManager.GetString("oet_prop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal OET (en trabajo, no cubierto por otras categorías).
        /// </summary>
        public static string oet_prop10 {
            get {
                return ResourceManager.GetString("oet_prop10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string oet_prop11 {
            get {
                return ResourceManager.GetString("oet_prop11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigación (con proyecto en la estación).
        /// </summary>
        public static string oet_prop2 {
            get {
                return ResourceManager.GetString("oet_prop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de pregrado.
        /// </summary>
        public static string oet_prop3 {
            get {
                return ResourceManager.GetString("oet_prop3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de posgrado.
        /// </summary>
        public static string oet_prop4 {
            get {
                return ResourceManager.GetString("oet_prop4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de extensión universitaria.
        /// </summary>
        public static string oet_prop5 {
            get {
                return ResourceManager.GetString("oet_prop5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa de Educación Ambiental.
        /// </summary>
        public static string oet_prop6 {
            get {
                return ResourceManager.GetString("oet_prop6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitante de historial natural.
        /// </summary>
        public static string oet_prop7 {
            get {
                return ResourceManager.GetString("oet_prop7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento especial-reunión.
        /// </summary>
        public static string oet_prop8 {
            get {
                return ResourceManager.GetString("oet_prop8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodista (reportero, escritor, filmación).
        /// </summary>
        public static string oet_prop9 {
            get {
                return ResourceManager.GetString("oet_prop9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propósito.
        /// </summary>
        public static string oet_proposito {
            get {
                return ResourceManager.GetString("oet_proposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propósito de la Visita.
        /// </summary>
        public static string oet_propositoTitulo {
            get {
                return ResourceManager.GetString("oet_propositoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricciones Dietarias y Alergias.
        /// </summary>
        public static string oet_resTitulo {
            get {
                return ResourceManager.GetString("oet_resTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante.
        /// </summary>
        public static string oet_rol1 {
            get {
                return ResourceManager.GetString("oet_rol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor(a).
        /// </summary>
        public static string oet_rol2 {
            get {
                return ResourceManager.GetString("oet_rol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinador.
        /// </summary>
        public static string oet_rol3 {
            get {
                return ResourceManager.GetString("oet_rol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistente.
        /// </summary>
        public static string oet_rol4 {
            get {
                return ResourceManager.GetString("oet_rol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string oet_rol5 {
            get {
                return ResourceManager.GetString("oet_rol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string oet_sexo {
            get {
                return ResourceManager.GetString("oet_sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin restricción.
        /// </summary>
        public static string oet_sinrestr {
            get {
                return ResourceManager.GetString("oet_sinrestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo para Participantes de Cursos.
        /// </summary>
        public static string oet_solocursos {
            get {
                return ResourceManager.GetString("oet_solocursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string oet_telefono {
            get {
                return ResourceManager.GetString("oet_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Registro.
        /// </summary>
        public static string oet_titulo {
            get {
                return ResourceManager.GetString("oet_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título (Sr., Sra., Dr., otro).
        /// </summary>
        public static string oet_tituloPer {
            get {
                return ResourceManager.GetString("oet_tituloPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegano.
        /// </summary>
        public static string oet_vegano {
            get {
                return ResourceManager.GetString("oet_vegano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetariano.
        /// </summary>
        public static string oet_vege {
            get {
                return ResourceManager.GetString("oet_vege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He sido debidamente informado(a) que la visita a las instalaciones de la Organización para Estudios Tropicales (OET) conlleva a riesgos inherentes a estaciones biológicas, tales como transitar por senderos o áreas resbalosas, húmedas y cubiertas de follaje y árboles circundantes. Asimismo, que en la zona a visitar existen serpientes y otros animales con el consabido riesgo de mordeduras y que puedan darse picaduras de insectos de cualquier naturaleza. También manifiesto que no tengo ningún impedimento de sa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oet_waiver {
            get {
                return ResourceManager.GetString("oet_waiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renuncia de Responsabilidad.
        /// </summary>
        public static string oet_waiverTitulo {
            get {
                return ResourceManager.GetString("oet_waiverTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string paisInst {
            get {
                return ResourceManager.GetString("paisInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo.
        /// </summary>
        public static string placeholder_ej {
            get {
                return ResourceManager.GetString("placeholder_ej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Reservación.
        /// </summary>
        public static string reservacion {
            get {
                return ResourceManager.GetString("reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Lenguaje.
        /// </summary>
        public static string seleccionarLen {
            get {
                return ResourceManager.GetString("seleccionarLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string tituloError {
            get {
                return ResourceManager.GetString("tituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrega Institución.
        /// </summary>
        public static string tituloInst {
            get {
                return ResourceManager.GetString("tituloInst", resourceCulture);
            }
        }
    }
}
