---------------------------USUARIO
CREATE TABLE "USUARIO" (	
  "ID"                  NUMBER(32,0) NOT NULL ENABLE, 
	"NOMBRE"              VARCHAR2(40 BYTE), 
	"APELLIDO"            VARCHAR2(40 BYTE), 
	"EMAIL"               VARCHAR2(40 BYTE), 
	"USUARIO"             VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CONTRASENA"          VARCHAR2(40 BYTE) NOT NULL ENABLE, 
  CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
);
/
CREATE SEQUENCE USUARIO_SEQ
  MINVALUE 0 
  START WITH     0
  INCREMENT BY   1
  NOCACHE
  NOCYCLE;
/ 
CREATE OR REPLACE TRIGGER "USUARIO_T" 
BEFORE INSERT ON USUARIO FOR EACH ROW
BEGIN
  SELECT USUARIO_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "USUARIO_T" ENABLE;
/ 

---------------------------PERSONA
CREATE TABLE "PERSONA" (
  "CEDULA"              NUMBER(9,0),
  "NOMBRE"              VARCHAR2(200 BYTE),
  "APELLIDO"            VARCHAR2(200 BYTE),
  "EMAIL"               VARCHAR2(200 BYTE),
  "TELEFONO"            VARCHAR2(150 BYTE),
  "NACIONALIDAD"        VARCHAR2(150 BYTE),
  "PAIS"                VARCHAR2(150 BYTE),
  "CIUDAD"              VARCHAR2(150 BYTE),
  "DIRECCION"           VARCHAR2(400 BYTE),
  "POSICION"            VARCHAR2(150 BYTE),
  "INSTITUCION"         VARCHAR2(150 BYTE),
  "TITULO"              VARCHAR2(150 BYTE),
  "ROL"                 VARCHAR2(150 BYTE),
  "GENERO"              CHAR,
  "COD_POSTAL"          VARCHAR2(150 BYTE),
  CONSTRAINT "PERSONA_PK" PRIMARY KEY ("CEDULA")
);

---------------------------INFOVISITA
--ALTER TABLE RESERVACION ADD CONSTRAINT RESERVACION_PK PRIMARY KEY (ID);
CREATE TABLE "INFOVISITA" (
  --DATOS DEL CONTACTO
  "ID_RESERVACION"      VARCHAR2(255 BYTE),
  "CEDULA"              NUMBER(9,0),
	"NOMBRE_EMERGENCIA"   VARCHAR2(400 BYTE), 
	"TEL_EMERGENCIA"      VARCHAR2(150 BYTE), 
	"EMAIL_EMERGENCIA"    VARCHAR2(150 BYTE), 
  "REL_EMERGENCIA"      VARCHAR2(150 BYTE), 
	"COMIDA"              VARCHAR2(300 BYTE), 
  "DIETA"               VARCHAR2(150 BYTE),
  "OBSERVACIONES_DIETA" VARCHAR2(150 BYTE),
  "ALERGIAS"            VARCHAR2(150 BYTE),
  "PROPOSITO"           VARCHAR2(150 BYTE), 
  "OTRO_PROPOSITO"      VARCHAR2(150 BYTE), 
  "COMO_ENTERO"         VARCHAR2(150 BYTE),
  "FECHA"               DATE,
  --ESTUDIANTES Y PROFES
  NOMBRE_CURSO          VARCHAR2(50 BYTE),
  NUMERO_CURSO          VARCHAR2(30 BYTE),
  ROL_CURSO             VARCHAR2(20 BYTE) ,
  --INVESTIGADORES
  NOMBRE_PROYECTO       VARCHAR2(50 BYTE),
  INVERSIONES           VARCHAR2(50 BYTE),
  FUENTE                VARCHAR2(50 BYTE),
  RESOLUCION            VARCHAR2(30 BYTE),
  PERMISO               VARCHAR2(30 BYTE),
  EXPIRACION            DATE,
  CONSTRAINT "INFOVISITA_PK" PRIMARY KEY ("CEDULA","ID_RESERVACION"),
  CONSTRAINT "INFOVISITA_RESERVA_FK" FOREIGN KEY ("ID_RESERVACION") REFERENCES RESERVACION(ID),
  CONSTRAINT "INFOVISITA_PERSONA_FK" FOREIGN KEY ("CEDULA") REFERENCES PERSONA(CEDULA)
);
/
