--ESQUEMA: CONTACTOS

-----------------------------------------------------------------------------------------------------------------GRANTS
GRANT SELECT ON CAT_INSTITUCION TO REGISTRO;
GRANT INSERT ON CAT_INSTITUCION TO REGISTRO;
GRANT SELECT ON STUDENT_ACADEMIC_DEGREE TO REGISTRO;
GRANT SELECT ON STUDENT TO REGISTRO;
GRANT SELECT ON CONTACTO TO REGISTRO;
GRANT SELECT ON CAT_ACADEMIC_DEGREE TO REGISTRO;
GRANT SELECT ON CAT_PAISES TO REGISTRO;

---
CREATE OR REPLACE TRIGGER "CONTACTOS".CAT_INSTITUCION_TRG BEFORE INSERT ON CAT_INSTITUCION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CAT_INSTITUCION IS NULL OR :NEW.CAT_INSTITUCION < 0 THEN
      SELECT CAT_INSTITUCION_SEQ.NEXTVAL INTO :NEW.CAT_INSTITUCION FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;