--ESQUEMA: CONTACTOS

-----------------------------------------------------------------------------------------------------------------GRANTS
GRANT SELECT ON CAT_INSTITUCION TO REGISTRO;
GRANT SELECT ON STUDENT_ACADEMIC_DEGREE TO REGISTRO;
GRANT SELECT ON STUDENT TO REGISTRO;
GRANT SELECT ON CONTACTO TO REGISTRO;
GRANT SELECT ON CAT_ACADEMIC_DEGREE TO REGISTRO;
GRANT SELECT ON CAT_PAISES TO REGISTRO;

COMMIT;