drop  table preregistroContacto
/
create table preregistroContacto(
  --DATOS DEL CONTACTO
	"CONTACTO" NUMBER(10,0), 
	"TYPE" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"BIRTH_DAY" DATE, 
	"BIRTH_PLACE" VARCHAR2(400 BYTE), 
	"INSTITUTION" VARCHAR2(400 BYTE), 
	"CATEGORY" VARCHAR2(150 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(150 BYTE), 
	"PHONE_AREA_CODE" VARCHAR2(50 BYTE), 
	"FAX" VARCHAR2(150 BYTE), 
	"FAX_AREA_CODE" VARCHAR2(50 BYTE), 
	"EMERGENCY_CONTACT1" VARCHAR2(400 BYTE), 
	"EMERGENCY_NUMBER1" VARCHAR2(150 BYTE), 
	"EMERGENCY_E_MAIL1" VARCHAR2(150 BYTE), 
	"EMERGENCY_CONTACT2" VARCHAR2(400 BYTE), 
	"EMERGENCY_NUMBER2" VARCHAR2(150 BYTE), 
	"EMERGENCY_E_MAIL2" VARCHAR2(150 BYTE), 
	"E_MAIL" VARCHAR2(150 BYTE), 
	"IDENTIFICATION_TYPE" NUMBER(10,0), 
	"IDENTIFICATION" VARCHAR2(200 BYTE), 
	"EXPIRATION_DATE" DATE, 
	"COUNTRY_BIRTH" VARCHAR2(20 BYTE), 
	"NACIONALITY" VARCHAR2(400 BYTE), 
	"ETHNIC_GROUP" VARCHAR2(150 BYTE), 
	"ADDRESS_L1" VARCHAR2(500 BYTE), 
	"AREA_OF_INTEREST" VARCHAR2(600 BYTE), 
	"ACADEMIC_DEGREE" VARCHAR2(800 BYTE), 
	"SECRET_QUESTION" VARCHAR2(150 BYTE), 
	"ANSWER" VARCHAR2(150 BYTE), 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"GRUPO" VARCHAR2(20 BYTE), 
	"EMERGENCY_NUMBER1_CODE" VARCHAR2(50 BYTE), 
	"EMERGENCY_NUMBER2_CODE" VARCHAR2(50 BYTE), 
	"HOME_PHONE" VARCHAR2(150 BYTE), 
	"HOME_PHONE_AREA" VARCHAR2(50 BYTE), 
	"ADDRESS_COUNTRY" VARCHAR2(20 BYTE), 
	"ADDRESS_L2" VARCHAR2(500 BYTE), 
	"CITY" VARCHAR2(300 BYTE), 
	"STATE" VARCHAR2(300 BYTE), 
	"ZIP_CODE" VARCHAR2(20 BYTE), 
	"CAT_TIPO_ESTUDIANTE" NUMBER(10,0), 
	"STATION" VARCHAR2(30 BYTE), 
	"NO_DIETARY_RESTRICTIONS" NUMBER(1,0) DEFAULT 0, 
	"VEGETARIAN" NUMBER(1,0) DEFAULT 0, 
	"VEGAN" NUMBER(1,0) DEFAULT 0, 
	"BEEF" NUMBER(1,0) DEFAULT 0, 
	"CHICKEN" NUMBER(1,0) DEFAULT 0, 
	"PORK" NUMBER(1,0) DEFAULT 0, 
	"FISH" NUMBER(1,0) DEFAULT 0, 
	"OTHER_DIETARY" VARCHAR2(400 BYTE) DEFAULT NULL, 
	"COUNTRY_EMITS" VARCHAR2(20 BYTE), 
	"CREADO" DATE DEFAULT sysdate, 
	"MODIFICADO" DATE, 
	"NICKNAME" VARCHAR2(150 BYTE), 
	"DEPARTAMENT" VARCHAR2(400 BYTE), 
	"POSITION" VARCHAR2(400 BYTE), 
	"SKYPE" VARCHAR2(400 BYTE), 
	"WEBSITE" VARCHAR2(1000 BYTE), 
	"CKOTHER_DIETARY_RESTRIC" NUMBER(1,0), 
	"TXOTHER_DIETARY_RESTRIC" VARCHAR2(1000 BYTE), 
	"PRIN" NUMBER(1,0) DEFAULT 0, 
	"RELATIONSHIP_CONTACT1" VARCHAR2(1000 BYTE), 
	"RELATIONSHIP_CONTACT2" VARCHAR2(1000 BYTE), 
	"INSURANCE_COMPANY" VARCHAR2(1000 BYTE), 
	"INSURANCE_NUMBER" VARCHAR2(100 BYTE), 
	"INSURANCE_EXPIRATION" DATE, 
	"ESPECIALIDAD" VARCHAR2(1000 BYTE), 
	"DATO_ESTACION" NUMBER(1,0) DEFAULT 0, 
	"CONTACTO_RESERVAS" VARCHAR2(30 BYTE) DEFAULT 0, 
	"SHARE_INFORMATION" VARCHAR2(1 BYTE) DEFAULT 0, 
	"PHONE_COUNTRY_CODE" VARCHAR2(20 BYTE), 
	"FAX_COUNTRY_CODE" VARCHAR2(20 BYTE), 
	"EMERGENCY_COUNTRY_NUM_CODE1" VARCHAR2(20 BYTE), 
	"EMERGENCY_COUNTRY_NUM_CODE2" VARCHAR2(20 BYTE), 
	"HORA_CREACION" VARCHAR2(100 BYTE) DEFAULT CURRENT_TIMESTAMP, 
	"E_MAIL2" VARCHAR2(150 BYTE),
    
  --DATOS DEL PREREGISTRO
  numpreregistro number(10,0),
  idreservacion varchar2(255 byte),
  proposito char,
  idgrupo varchar2(30 byte),
  comoentero varchar2(50 byte),
  fecha date,
  
  --estudiantes y profes
  nomcurso varchar2(50 byte),
  numcurso varchar2(30 byte),
  rolcurso char,
  
  --investigadores
  nomproyecto varchar2(50 byte),
  inversiones varchar2(50 byte),
  fuente varchar2(50 byte),
  resolucion varchar2(30 byte),
  permiso varchar2(30 byte),
  expiracion date,
  alergias varchar2 (100 byte) 
);
/
ALTER TABLE preregistroContacto ADD CONSTRAINT preregistro_pk PRIMARY KEY (numpreregistro,CONTACTO);
/
drop SEQUENCE PREREGISTROCONTACTO_P_SEQ
/
CREATE SEQUENCE PREREGISTROContacto_P_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
/
CREATE OR REPLACE TRIGGER "PREREGISTROCONTACTO_P_TRN" before
INSERT ON "PREREGISTROCONTACTO" FOR EACH row BEGIN
IF inserting THEN
  IF :NEW."NUMPREREGISTRO" IS NULL THEN
    SELECT PREREGISTRO_SEQ.nextval INTO :NEW."NUMPREREGISTRO" FROM dual;
  END IF;
END IF;
END;
/
ALTER TRIGGER "PREREGISTROCONTACTO_P_TRN" ENABLE;
/
drop SEQUENCE PREREGISTROCONTACTO_C_SEQ
/
CREATE SEQUENCE PREREGISTROCONTACTO_C_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
/
CREATE OR REPLACE TRIGGER "PREREGISTROCONTACTO_C_TRN" before
INSERT ON "PREREGISTROCONTACTO" FOR EACH row BEGIN
IF inserting THEN
  IF :NEW."NUMPREREGISTRO" IS NULL THEN
    SELECT PREREGISTROCONTACTO_C_SEQ.nextval INTO :NEW."NUMPREREGISTRO" FROM dual;
  END IF;
END IF;
END;
/
ALTER TRIGGER "PREREGISTROCONTACTO_C_TRN" ENABLE;