CREATE OR REPLACE FORCE VIEW "V_EMPLEADOS" 
AS
 SELECT
   IDEMPLEADO   AS ID,
   NOMBRE AS NOMBRE,
   APELLIDOS  AS APELLIDOS,
   EMAIL     AS EMAIL,
   SEXO     AS SEXO,
   IDENTIFICACION AS IDENTIFICACION,
   IDNACIONALIDAD AS NACIONALIDAD,
   ESTADOCIVIL AS ESTADOCIVIL
 FROM
   FINANCIERO.EMPLEADOS;